version: '2'

services:

  sidekiq:
    image: magic-cards:dev
    networks:
      - backend
      - default
    external_links:
      - postgres:postgres
      - redis:redis
    command: script/sidekiq
    volumes:
      - 'sidekiq-sync:/app:nocopy'
    env_file:
      - '.env'
  website:
    image: magic-cards:dev
    networks:
      - backend
      - default
    external_links:
      - postgres:postgres
      - redis:redis
    command: script/server
    volumes:
      - 'website-sync:/app:nocopy'
    ports:
      - '3000:3000'

  cable:
    image: magic-cards:dev
    networks:
      - backend
      - default
    external_links:
      - postgres:postgres
      - redis:redis
    command: script/cable
    image: magic-cards:dev
    ports:
      - '28080:28080'
    volumes:
      - 'cable-sync:/app:nocopy'

volumes:
  bundle:
  website-sync: &sync
    external: true
  cable-sync: *sync
  sidekiq-sync: *sync

networks:
  default:
    external:
      name: frontend
  backend:
    external: true
