#!/usr/bin/env sh

docker build \
       --no-cache \
       --pull \
       -t magic-cards-website \
       -f script/docker/Dockerfile .
docker build \
       -t magic-cards-sidekiq \
       -f script/docker/Dockerfile .
docker build \
       -t magic-cards-cable \
       -f script/docker/Dockerfile .

