#!/usr/bin/env sh

set -eo pipefail


docker-compose -f ~/Projects/magic-cards/docker-compose-backend.yml \
               -f ~/Projects/magic-cards/docker-compose.yml \
               run --rm sidekiq script/update

docker-compose -f ~/Projects/magic-cards/docker-compose-backend.yml \
               -f ~/Projects/magic-cards/docker-compose.yml \
               "$@"
