#!/usr/bin/env sh

### Docker containers that wish to access services running on the host (this mac)
### need a known IP address for the lo0 interface, 127.0.0.1 will not work.
###
### This adds an alias IP to the lo0 interface of the host.
### It copies a plist script to /Library/LaunchDaemons and enables it via launchctl,
### so that this alias will be added automatically at boot time in future.
###

ALIAS_IP="${ALIAS_IP:-169.254.254.254}"

LO0_IPS=$( ifconfig | grep -A6 lo0: | grep 'inet '  | cut -d ' ' -f 2 )


if [[ "${LO0_IPS}" =~ "${ALIAS_IP}" ]]; then
  exit 0
else
  echo "We need to add and persist an alias IP to the lo0 network interface."
  echo "Please enter your local sudo password to complete this one-time task:"
  sudo /sbin/ifconfig lo0 alias ${ALIAS_IP}
  NAME=co.cozy.add-lo0-alias-for-docker
  FILE="${NAME}.plist"
  DIR=./script

  tee $DIR/$FILE <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>co.cozy.add-lo0-alias-for-docker</string>
  <key>ProgramArguments</key>
  <array>
    <string>/sbin/ifconfig</string>
    <string>lo0</string>
    <string>alias</string>
    <string>${ALIAS_IP}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
PLIST


  sudo cp ${DIR}/${FILE} /Library/LaunchDaemons/

  sudo chown root:wheel /Library/LaunchDaemons/$FILE
  launchctl list | grep $NAME && launchctl unload /Library/LaunchDaemons/$FILE
  sleep 1
  launchctl load /Library/LaunchDaemons/$FILE
  rm ${DIR}/${FILE}
fi
